Sierracode/-tg-station

- code/game/gamemodes/nuclear/blackops_items.dm
At least for non-syndicate baloon packs
> Fix balooning to centcomm

- code/modules/mob/mob_helpers.dm
This doesn't have an impact on the regular output, but makes saved logs look better
> Fix ghost_notify span not being properly closed

- _maps/RandomZLevels/spacehotel.dmm
This makes the loader stop runtiming
> Fix spacehotel using non-existant turf type

- code/modules/research/xenoarchaeology/artifact/artifact_autocloner.dm
- code/modules/research/xenoarchaeology/artifact/artifact_replicator.dm
Also fix the autopod from looking unpowered
> Make some of the artifact that look wrenchable to the floor actually wrenchable

- code/modules/reagents/Chemistry-Machinery.dm
This addresses the things posted in https://github.com/Zaers/-tg-station/issues/267
As outlined, this allows the machine to empty beakers, upload viruses and vaccines from the analysis screen, transfer the chemicals stored in the machine into the beaker at greater quantities than one unit at a time and to delete stored diseases and vaccines (perhaps there could be a confirmation for deleting and also maybe a changelog)
> Enhance the PANDEMIC UI according to feedback

- code/modules/mob/living/carbon/human/human.dm
This means that a sec officer could be stripped of his ID and still be able to set arrest status if he had the inputs up before his ID got removed
> Fix the sechud ID check not caring for any changes after checking once

- code/modules/mob/mob_movement.dm
- interface/skin.dmf
Specifically this makes movement more responsive due to not using the BYOND default movement procs
> Port an tg enhancement to movement handling procs

- code/__HELPERS/lists.dm
It doesn't clobber things anymore
> Port some changes that make is_type_in_list() behave better

- code/controllers/configuration.dm
- code/modules/admin/player_notes.dm
- code/modules/client/client procs.dm
- config/config.txt
- interface/skin.dmf
> Port MSO's cid randomizer checker

- code/__DEFINES/lighting.dm
- code/controllers/master_controller.dm
- code/controllers/subsystem/lighting.dm
- code/game/asteroid.dm
- code/game/turfs/turf.dm
- code/modules/lighting/light_source.dm
- code/modules/lighting/lighting_overlay.dm
- code/modules/lighting/lighting_system.dm
- code/modules/lighting/lighting_turf.dm
- code/modules/mining/mine_turfs.dm
- code/modules/shuttle/shuttle.dm
Also removes some unused code related to LIGHTING_RESOLUTION
> Fix some oddities with the lighting system and make it more robust

- code/modules/mob/living/simple_animal/hostile/mimic.dm
- code/modules/mob/living/simple_animal/hostile/mining_mobs.dm
Also fixes a runtime when the ranged mimic has no gun
> Guarantee ranged cooldown checking for some mobs

- code/controllers/master_controller.dm
- code/game/asteroid.dm
It's supposed to generate up to `max_secret_rooms` but it was only generating one
> Fix MC only making one mining secret

- code/modules/surgery/amputation.dm
This makes it print a message when you succeed
> Improve feedback on the stump cleanup surgery step

- code/game/gamemodes/abduction/gland.dm
- code/modules/organs/organs.dm
this is actually important, even if it doesn't look like it
> Fix issues with gland insertion for abductors

- code/game/gamemodes/objective.dm
- code/modules/mob/living/carbon/brain/posibrain.dm
Also fixes identity theft wanting ID of nonhumans
Because the mind isn't transferred anymore this fixes #39
> Fix minds being transferred into posibrains

- code/game/machinery/cloning.dm
This just reorders some operations to make the code there work, it should probably be changelogged through
> Fix cloner granting mutations and then immediately taking them away

- code/game/machinery/computer/buildandrepair.dm
- code/game/machinery/computer/camera_advanced.dm
- code/modules/research/designs/comp_board_designs.dm
Added advanced security cameras board to RnD. They were already coded in but not used. Works like AI view. This board will require Engineering 6, Data 6, EMP 7 and diamonds to make. I think it should be fine in balance because of this.
> Added advanced security cameras

- code/modules/hydroponics/biogenerator.dm
Seems to resolve https://github.com/Sierracode/-tg-station/issues/62
> Appears to fix biogenerator visual error

- code/modules/power/solar.dm
> Stop solar panels assemblies from being stackable in turfs

- code/controllers/configuration.dm
- interface/interface.dm
- interface/skin.dmf
blame the byond skin editor for the gorillion deletions
> Add the music button to the UI and also fix some minor issues with it

- code/game/objects/structures/safe.dm
Sends user message when nonhuman and attempting to use safe
https://github.com/Sierracode/-tg-station/issues/59
> Safe message

- code/game/objects/structures/tank_dispenser.dm
> Allow borgs to use tank dispensers

- code/game/gamemodes/abduction/machinery/camera.dm
- code/game/machinery/computer/camera_advanced.dm
Maybe this should help out with the abduction camera problems (#88)
At the very least, it should help out with the camera console being inaccessible
> Make some adv. camera conditions more robust

- code/modules/mob/living/silicon/mommi/inventory.dm
- code/modules/mob/living/silicon/robot/inventory.dm
This might help out with #95 
Do note that while I couldn't reproduce #95 with this even after constantly taking and storing things while interacting with things, this doesn't necessarily mean I managed to actually fix it
> Remove unnecessary contents manipulation in silicon inventory

- _maps/map_files/MetaStation/MetaStation.v40D.dmm
And also fix the line endings in the map file to be properly LF
Fixes #114
> Change wall where the toxins test camera is mounted to indestructible type

- code/modules/surgery/limb_transplant.dm
> Stop transplanted limbs from flopping out to the floor

- code/modules/research/rdconsole.dm
Fixes https://github.com/Sierracode/-tg-station/issues/127
> Vultraz is a retard

- code/datums/diseases/advance/advance.dm
- html/changelogs/zaers-virus.yml
This also demonstrates an yml changelog file
> Fix virus resist not rounding for indexing

- code/_compile_options.dm
- code/controllers/subsystem/ticker.dm
- code/crew_objective.dm
- code/miscreant_objectives.dm
- code/modules/mob/new_player/new_player.dm
- tgstation.dme
Ports objectives from gooncode. Not many objectives since most of the objectives from that codebase don't have anything to do with ours; those objectives have been commented out. Might cause runtime errors, but none as far as I've tested.
> Goon objectives

- code/controllers/subsystem/ticker.dm
- code/datums/ai_laws.dm
- code/datums/helper_datums/robo.dm
- code/modules/mob/living/silicon/mommi/death.dm
- code/modules/mob/living/silicon/robot/death.dm
- tgstation.dme
Fuck controllers.
https://github.com/Sierracode/-tg-station/issues/153
> Ticker for gibbed sillies.
